# Generated by Codex on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("langgraph_integration", "0025_alter_llmconfig_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfig",
            name="shared_daily_token_limit",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                verbose_name="共享成员每日 Token 限额",
            ),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="shared_total_token_limit",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                verbose_name="共享总 Token 限额",
            ),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="shared_expires_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="共享有效期",
            ),
        ),
    ]
