# Generated by Codex on 2026-04-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("langgraph_integration", "0026_llmconfig_shared_limits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMTokenUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_name", models.CharField(blank=True, default="", max_length=255, verbose_name="配置名称快照")),
                ("provider", models.CharField(blank=True, default="", max_length=50, verbose_name="供应商快照")),
                ("model_name", models.CharField(blank=True, default="", max_length=255, verbose_name="模型名称快照")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("langgraph_chat", "AI 对话"),
                            ("api_automation", "AI 接口自动化"),
                            ("requirements_review", "需求评审"),
                            ("ui_automation", "UI 自动化"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="使用来源",
                    ),
                ),
                ("prompt_tokens", models.BigIntegerField(default=0, verbose_name="输入 Token")),
                ("completion_tokens", models.BigIntegerField(default=0, verbose_name="输出 Token")),
                ("total_tokens", models.BigIntegerField(default=0, verbose_name="总 Token")),
                ("request_count", models.PositiveIntegerField(default=1, verbose_name="请求次数")),
                ("usage_date", models.DateField(default=django.utils.timezone.localdate, verbose_name="使用日期")),
                ("is_shared_access", models.BooleanField(default=False, verbose_name="是否共享调用")),
                ("session_id", models.CharField(blank=True, default="", max_length=255, verbose_name="会话ID")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="附加元数据")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "llm_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="token_usages",
                        to="langgraph_integration.llmconfig",
                        verbose_name="LLM 配置",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_token_usages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Token 使用记录",
                "verbose_name_plural": "LLM Token 使用记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="llmtokenusage",
            index=models.Index(fields=["usage_date", "user"], name="langgraph_i_usage_d_57d86f_idx"),
        ),
        migrations.AddIndex(
            model_name="llmtokenusage",
            index=models.Index(fields=["usage_date", "llm_config"], name="langgraph_i_usage_d_607e7c_idx"),
        ),
        migrations.AddIndex(
            model_name="llmtokenusage",
            index=models.Index(fields=["source", "usage_date"], name="langgraph_i_source_07fb14_idx"),
        ),
    ]
