# Generated by Django 5.2 on 2026-04-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui_automation", "0006_uiactuator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uiaiexecutionrecord",
            name="heartbeat_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最近心跳时间"
            ),
        ),
        migrations.AddField(
            model_name="uiaiexecutionrecord",
            name="worker_token",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="工作节点令牌"
            ),
        ),
        migrations.CreateModel(
            name="UiActuatorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actuator_id",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="执行器ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="执行器名称",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True,
                        default="unknown",
                        max_length=128,
                        verbose_name="执行器 IP",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        default="web_ui",
                        max_length=64,
                        verbose_name="执行器类型",
                    ),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="是否可用")),
                ("debug", models.BooleanField(default=False, verbose_name="调试模式")),
                (
                    "browser_type",
                    models.CharField(
                        blank=True,
                        default="chromium",
                        max_length=32,
                        verbose_name="浏览器类型",
                    ),
                ),
                (
                    "headless",
                    models.BooleanField(default=False, verbose_name="无头模式"),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="版本号"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(default=True, verbose_name="是否在线"),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="连接时间"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近心跳时间"
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="断开时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ui_actuator_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI 执行器会话",
                "verbose_name_plural": "UI 执行器会话",
                "db_table": "ui_actuator_session",
                "ordering": ["actuator_id"],
            },
        ),
    ]
