# Generated by Django 5.2 on 2026-04-02 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_automation", "0006_alter_apiexecutionrecord_run_id_and_more"),
        ("projects", "0004_remove_project_password_remove_project_system_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiCaseGenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("selected", "selected"),
                            ("collection", "collection"),
                            ("project", "project"),
                        ],
                        default="selected",
                        max_length=20,
                        verbose_name="生成范围",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("generate", "generate"),
                            ("append", "append"),
                            ("regenerate", "regenerate"),
                        ],
                        default="generate",
                        max_length=20,
                        verbose_name="生成模式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("preview_ready", "preview_ready"),
                            ("applying", "applying"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("canceled", "canceled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "count_per_request",
                    models.PositiveIntegerField(
                        default=3, verbose_name="每个接口生成数量"
                    ),
                ),
                (
                    "request_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="目标接口 ID 列表"
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveIntegerField(default=0, verbose_name="进度百分比"),
                ),
                (
                    "progress_stage",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="当前阶段"
                    ),
                ),
                (
                    "progress_message",
                    models.TextField(blank=True, default="", verbose_name="阶段说明"),
                ),
                (
                    "cancel_requested",
                    models.BooleanField(default=False, verbose_name="是否请求停止"),
                ),
                (
                    "result_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="结果载荷"),
                ),
                (
                    "draft_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="预览草稿"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_generation_jobs",
                        to="api_automation.apicollection",
                        verbose_name="目标集合",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_case_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_case_generation_jobs",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "API 用例生成任务",
                "verbose_name_plural": "API 用例生成任务",
                "db_table": "api_automation_case_generation_job",
                "ordering": ["-created_at"],
            },
        ),
    ]
